version: '3.9'
name: smeepy

services:

  database-postgresql:
    image: postgres:latest
    container_name: Smeepy-Database-PostgreSQL
    restart: unless-stopped
    volumes:
      - smeepy-database-postgresql:/var/lib/postgresql/data
    networks:
      - smeepy-internal
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "9000:5432"

  database-redis:
    image: redis:latest
    container_name: Smeepy-Database-Redis
    restart: unless-stopped
    volumes:
      - smeepy-database-redis:/data
    networks:
      - smeepy-internal
    ports:
      - "9010:6379"



volumes:
  smeepy-database-postgresql:
  smeepy-database-redis:

networks:
  smeepy-internal: